apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springbootzipkin-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: springbootzipkin
    spec:
      containers:
      - name: springbootzipkin
        image: marcinkasinski/springbootzipkin
        ports:
        - name: nodejs-port
          containerPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: springbootzipkin
spec:
  type: NodePort
  ports:
  - port: 7777
    nodePort: 30777
    targetPort: 7777
    protocol: TCP
    name: http
  selector:
    app: springbootzipkin
---
# An Ingress with 2 hosts and 3 endpoints
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: springbootzipkin-ingress
spec:
  rules:
  - host: springbootzipkin
    http:
      paths:
      - path: /
        backend:
          serviceName: springbootzipkin
          servicePort: 7777
